### ISSUE TITLE
recursive by default?

### ISSUE THREAD

**Issue by yoshuawuyts** [timoxley/linklocal#18]
Would it make sense to make `-r` the default in `{link,list}`? I never use the non `-r` variant, and forgetting to include it can make a mess. All module related tools I know of `{npm,browserify}` also think of modules as being recursive.

I think if a `-R` flag (or similar) for non-recursive would be added it wouldn't even have to be considered a breaking change (non `-r` is mostly be for speed, right?). What do you think?

**Comment by timoxley** [comment]
mhmmm. I almost never use `rm` without `-r`.

**Comment by yoshuawuyts** [comment]
I hear what you're saying. Ghmmmmh. `rm` is a destructive operation though, having `-r` as a safety net makes sense I guess?

**Comment by yoshuawuyts** [comment]
Don't feel this is worth keeping an issue open about. Closing.
