### ISSUE TITLE
npm@3 warning spam on npm install after linklocal

### ISSUE THREAD

**Issue by wjordan** [timoxley/linklocal#24]
My project is receiving a massive amount of warning spam when using linklocal after upgrading to npm@3. Here's a simplified test-case bash script:

``` bash
mkdir linklocal-test-`npm -v`
cd linklocal-test-`npm -v`
npm init -f
mkdir a
cd a
npm init -f
npm i wordwrap
cd ..
npm i --save-dev linklocal
npm i --save ./a
npm i
`npm bin`/linklocal
npm i
```

This sequence of commands creates a simple local package dependency (`linklocal-test` package depends on `a` package, which lives in a subfolder). Here are the outputs of the final `npm i` command, comparing `npm i -g npm@2` versus `npm i -g npm@3`:

npm@2 (currently 2.14.15):

```
$ npm i
npm WARN package.json linklocal-test-2.14.15@1.0.0 No description
npm WARN package.json linklocal-test-2.14.15@1.0.0 No repository field.
npm WARN package.json linklocal-test-2.14.15@1.0.0 No README data
```

npm@3 (currently 3.5.3):

```
$ npm i
npm WARN skippingAction Module is inside a symlinked module: not running remove wordwrap@1.0.0 node_modules/a/node_modules/wordwrap
npm WARN update-linked node_modules/a needs updating to 1.0.0 from 1.0.0 but we can't, as it's a symlink
npm WARN linklocal-test-3.5.3@1.0.0 No description
npm WARN linklocal-test-3.5.3@1.0.0 No repository field.
```

the `skippingAction` warning appears for every single module in all locally-linked dependencies node_modules lists, and the `update-linked` warning appears for every locally-linked dependency.

Aside from the warning spam, everything _seems_ to still work properly. So for the meantime, my workaround is to run `npm --color=always i 2>&1 | grep -v "npm.*WARN.*\(skippingAction\|update-linked\)"` instead of `npm i` to manually filter out the extra warning spam.

**Comment by timoxley** [comment]
Not sure there's much linklocal can do for this, and since "Aside from the warning spam, everything seems to still work properly." then I think it's ok.
