### ISSUE TITLE
Does not support bundledDependencies(?)

### ISSUE THREAD

**Issue by OhDavit** [timoxley/linklocal#31]
local packages linked from bundledDependencies are not installed.

**Comment by timoxley** [comment]
Can you give an example of what you are trying to do?

**Comment by OhDavit** [comment]
hey, thanks for quick reply! my package looks similar:

 `      
         
          { "name": "TEST",
            "version": "0.0.1",
            "description": "",
             "scripts": {
               },
              "dependencies": {
               "rimraf": "^2.6.0"
            },

           "bundledDependencies": {
             "test-local-package": "file:../../xxlib/xxserver" 
             } 
         }
 `

And test-local-package is not being installed.

**Comment by timoxley** [comment]
Ok cool, why does it need to be in bundledDependencies​? Are you publishing to a registry?

**Comment by OhDavit** [comment]
thanks.
I am going to put there my local packages which are used across all my projects.

**Comment by timoxley** [comment]
Sure, though I think everything will work just fine if you use regular dependencies. Only real reason to use bundled is if you're publishing to a registry and need to include a forked dependency. If you're not publishing to a registry then there's not a lot of reason to use bundled deps.

**Comment by timoxley** [comment]
Please reopen if you have further questions 👍
