### ISSUE TITLE
Jenkin job throw linklocal.js error

### ISSUE THREAD

**Issue by danshmidt77** [timoxley/linklocal#33]
Linux base job throw linklocal.js error when attempting to run
"linklocal link -r && linklocal list -r | bulk -c 'npm install'"

/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_6.9.2/lib/node_modules/linklocal/bin/linklocal.js:100
  if (err) throw err
           ^

**Comment by timoxley** [comment]
@danshmidt77 what is the error?

**Comment by timoxley** [comment]
Please reopen if you continue to have this issue.
